#!/bin/bash

baseFileName=$(date +bookBarCodes_%Y_%m_%d)

echo ""
echo "creating: ${baseFileName}.kpz"
echo ""


rm -rf kpz/${baseFileName}.zip kpz/${baseFileName}.kpz

zip -r kpz/${baseFileName}.zip \
  Koha/Plugin/AllSaints/BookBarCodes \
  Koha/Plugin/AllSaints/BookBarCodes.pm

mv kpz/${baseFileName}.zip kpz/${baseFileName}.kpz

echo ""
echo done
echo ""